### ISSUE TITLE
Small gap on right side of pages.

### ISSUE THREAD

**Issue by jwr12135** [Cornerstone-Church/CAG-MainWebsite#169]
There is a small gap on the right side of the pages, "**About**, **Missions**, and **Give**" that you can scroll to. On the rest of the pages, if the screen width is between 800px and 835px the gap is created.

**Comment by silentsonata** [comment]
Hmmm....Yea I have been seeing this pop up all over the site. Any idea what is causing it?

**Comment by steamwings** [comment]
#182 contains a suggested fix, but it doesn't address the source of the gap.

**Comment by steamwings** [comment]
Okay I looked around a bit and my hunch was right. That margin goes away if you put everything into one of the `<div class="content">`. For some reason `width:100%` (for instance in the `#banner-tuesday` ruleset in give_style.css) doesn't seem to be working as expected.

**Comment by silentsonata** [comment]
@steamwings Thanks for looking into this! The commit has been pushed! 😄

**Comment by silentsonata** [comment]
Let keep this open as it roles out. Once the problem can be confirmed as fixed I'll close it.

**Comment by steamwings** [comment]
Looks like the hack worked for Give, but there's a (somewhat smaller) scrollable gap on About and Missions.

**Comment by silentsonata** [comment]
Hmm....I am not seeing it. Maybe it takes a little bit to apply sitewide due to cache?

**Comment by silentsonata** [comment]
@steamwings What browser and build are you seeing this in? Maybe I could download it and see if I can replicate it.

**Comment by silentsonata** [comment]
This ticket has been open for a while with no progress or reports. If this issue appears again we can open this back up.
