### ISSUE TITLE
Footer Link

### ISSUE THREAD

**Issue by silentsonata** [Cornerstone-Church/CAG-MainWebsite#19]
Several footer links are dead:
- Meet our Staff
- Partner Churches
- Give: Text
- All Ministry links

**Comment by silentsonata** [comment]
Has been fixed

**Comment by ZanyHunter** [comment]
Give Online link is broken in footer

**Comment by ZanyHunter** [comment]
Fixed. Footer was linking straight to https://app.easytithe.com/g3/, which shows a 404 until you go to https://app.easytithe.com/caggiving for the first time.

**Comment by silentsonata** [comment]
Has been pushed to release but it is still linking to /g3/ link instead of /caggiving/. Im thinking its a cache thing?

**Comment by ZanyHunter** [comment]
Hm. Links to /caggiving/ for me.

**Comment by silentsonata** [comment]
Alright it is now working on my end. Must have been cache.
