### ISSUE TITLE
Sermon Series logo on home page mobile

### ISSUE THREAD

**Issue by silentsonata** [Cornerstone-Church/CAG-MainWebsite#285]
The home page sermon logo is not sized right on mobile. The image is too large. On desktop its good. but mobile it needs to be smaller.

**Comment by ZanyHunter** [comment]
I have a couple ideas I'm working on to improve the resizing of that area that goes beyond changing the width percentage under the `@media` rule. Will update tomorrow (later today?)

**Comment by silentsonata** [comment]
👍
