### ISSUE TITLE
Youth Page - Social media elements should keep their title

### ISSUE THREAD

**Issue by silentsonata** [Cornerstone-Church/CAG-MainWebsite#290]
Social media elements on the youth page should keep their original header title instead of having two. When hovering over an element the large title is hidden and a smaller one appears. This functionality should be changed to only have the large title but when hovered over, instead of disappearing it moves to the top of the element.

Page: https://cag.org/ministries/fusion/#class-element

**Comment by ZanyHunter** [comment]
Possible fix in [issue-socialMedia](https://github.com/Cornerstone-Church/CAG-MainWebsite/tree/issue-socialMedia) branch.
Titles were set to a static position at the top of each menu element and the darkening transition was removed. If you still want the darkening transition, let me know and I can put it back and place the titles in front of it.

**Comment by ZanyHunter** [comment]
This seems to have made the buttons clickable through the closed menu on mobile (tested via device toolbar on Chrome). I'm not sure why.
To reproduce: Emulate touchscreen on a browser, and "tap" the lower center of any closed menu element. It should click the hidden button.

**Comment by silentsonata** [comment]
@ZanyHunter This is happening because, in the stylesheet, we are only changing the opacity. The element is still active just the translucency has changed. There are three possible ways to fix this.
1. Add visibility: hidden; to the hover and visibility: visible; to the element style.
2. Use a keyframe animation and implement display: none, and display: inline-block.
3. Use JS to disable the button when it is not at 100% opacity. (Not the best way)
This problem should be able to be completely solved through CSS. In fact, there might be code somewhere on the site that already has fixed this. 

Hope this helps!

**Comment by ZanyHunter** [comment]
Thanks for the help!
