### ISSUE TITLE
Social media images missing

### ISSUE THREAD

**Issue by ZanyHunter** [Cornerstone-Church/CAG-MainWebsite#295]
Instagram and YouTube background images are missing on Doulos page:
https://www.cag.org/ministries/doulos/

**Comment by ZanyHunter** [comment]
As a side note, should we unify the social media menus on all the pages? The Doulos one seems like it's the odd one out.

**Comment by silentsonata** [comment]
Good catch! Elevated this bug. I will check in with Miranda and see if we can get graphics for them. They must have disappeared with the merge.

As far as the social buttons, we are going to be redoing all of them at some point. Youth just wanted theirs specifically to look like that. What are you thoughts in making them all like the youth page?

**Comment by silentsonata** [comment]
Also take a look at #290

**Comment by ZanyHunter** [comment]
I found a commit with the images there. I'll snag them and replace them tonight.

**Comment by ZanyHunter** [comment]
Images were still there, but their titles were changed to add version numbers in commit 4c234f1. The references were changed on the Fusion page, but not on the Doulos page, leaving them broken. PR #296 fixes this.
Should we add some icons to the Doulos social media menu? They look rather bare at the moment. Not sure if it is worth it considering we are updating the social media menus altogether soon.

**Comment by silentsonata** [comment]
Awesome! Um I wouldn't bother with logos. Miranda is replacing it all anyway. We just need it to get through the weekend.
