### ISSUE TITLE
hold_it.js displaying content early

### ISSUE THREAD

**Issue by ZanyHunter** [Cornerstone-Church/CAG-MainWebsite#299]
`hold_it.js` is displaying content early and out of sync with `expire_it.js`, resulting in double buttons and other anomalies. Example below. Not sure how early it displays.
![image](https://user-images.githubusercontent.com/34586837/78465531-d22c2f00-76c4-11ea-9139-8e018768afdf.png)

**Comment by silentsonata** [comment]
Hmm good catch! I’m pretty sure I know exactly what it is. I’ll take this one on. 😁
