### ISSUE TITLE
Live not displaying live chat

### ISSUE THREAD

**Issue by ZanyHunter** [Cornerstone-Church/CAG-MainWebsite#300]
https://www.cag.org/live not displaying live chat. `&embed_domain` is incorrect. Currently is `cag.org`. Must be `www.cag.org`.

**Comment by ZanyHunter** [comment]
Actually, cag.org only gets redirected to www.cag.org on SOME browsers. Closing pull request for now.

**Comment by ZanyHunter** [comment]
I'm wondering if the `&embed_domain` url can be appended on the client side using JS `window.location.hostname`. Would that be a feasible solution?

**Comment by ZanyHunter** [comment]
@silentsonata, I have solved the issue... but it might not be the prettiest. If you could take a look at it in [issue-liveChat](https://github.com/Cornerstone-Church/CAG-MainWebsite/tree/issue-liveChat) at some point that'd be great!

Summary of changes:
- Removed `$chatURL` generation from PHP script
- Removed `src` attribute from `live-chat` element
- Created JS function that:
  1. Generates a live chat URL based on the PHP `$videoID` and the client's detected hostname, discovered with `window.location.hostname`
  2. Directly sets the `live-chat`'s `src` attribute to the generated URL
  3. Called JS function from within `<body>`'s `onload` attribute

It works with localhost (I tested by temporarily replacing CAG's channel ID with a random live YouTube channel)
I don't particularly like the static referencing of the HTML tag to change its attributes. I would have much preferred to directly return the string in the function and set the `src` tag to that function, but that was not working for me. Very new at this, so I might have (more like probably have) approached this from the complete wrong direction. Let me know what you think.

**Comment by silentsonata** [comment]
Nice solution! I was looking through it and added a description for the function getChatLink() and also fixed a bit of the formating. Also I got rid of the test function? Im guessing you were using it to test something? But anyway! In terms of the window.location.hostname, is there a reason why we are using this instead of just putting a static variable in?

**Comment by ZanyHunter** [comment]
I used window.location.hostname because it will return `www.cag.org` or `cag.org`, depending on what subdomain the user uses, just to make the YouTube embed happy. Do you have another solution? I'm super open to suggestions.

**Comment by silentsonata** [comment]
@ZanyHunter Ahh that makes perfect sense! Great find! So yea! looked over what you had so far and everything looks great! Whenever you feel like its ready go ahead and make a pull request and I will get it in there!

**Comment by ZanyHunter** [comment]
Ohhh, right. I forgot about that test function. Whoops!
