### ISSUE TITLE
Chrome deprecating cookies without SameSite attribute

### ISSUE THREAD

**Issue by ZanyHunter** [Cornerstone-Church/CAG-MainWebsite#305]
Chrome will be blocking cookies not set with `SameSite=None` and `Secure` attributes. All YouTube embeds are currently throwing these warnings on the Chrome v80 console.

**Comment by ZanyHunter** [comment]
Everything I'm seeing suggests that YouTube is the one that needs to make these adjustments. There are HTTP response additions that can be done to block those cookies, but that is just a band-aid workaround.

**Comment by silentsonata** [comment]
Hmm interesting. Thanks for looking into this! I say we just leave it and keep an eye on the logs see if they resolve it. Let's leave this issue open.
