### ISSUE TITLE
Update inconsistencies on social buttons

### ISSUE THREAD

**Issue by silentsonata** [Cornerstone-Church/CAG-MainWebsite#308]
This thought was entertained earlier and I think we should act on it. Let's update all of the social buttons to work as they do on the fusion page. 
https://cag.org/ministries/fusion/
And if possible let's update all of the elements that are similar to it also. Like these pages for example:
https://cag.org/ministries/men/
https://cag.org/ministries/cafe/

**Comment by ZanyHunter** [comment]
I'll take care of it! In the cafe menu, it looks like there is only one section. How do you want the menu to be sectioned on that page? (Also should the meal info be temporarily removed while it's closed?)

**Comment by silentsonata** [comment]
Hm yes good call on the menu. I can take care of that. It is getting the data from firebase. Im honestly not sure what to do for the menu. Since it is only one item I think we need to create a whole other element for it. @ZanyHunter What do you think?

**Comment by silentsonata** [comment]
We could always have a video chat tomorrow and come up with a new element.

**Comment by ZanyHunter** [comment]
Sure, video call works. Check out [issue-socialMedia](https://github.com/Cornerstone-Church/CAG-MainWebsite/tree/issue-socialMedia) branch if you have a chance. It contains new menus for Doulos, Men, and Women. I know there are more, but before I get too deep into it I have a few thoughts and questions:
- I feel we should make the menu more versatile, universal, and easy-to-use by doing these things:
  - Putting the menu style in site-wide `style.css`
  - Making expanded menu auto-size according to size of content within
  - Make images not resize during expansion animation (especially on mobile) - make them the expanded size from the beginning so they don't move around
  - Darken collapsed background images or somehow make title text more legible
- Should we put most list items in this menu format? Pages like https://cag.org/ministries/lifegroups/

What are your thoughts, @silentsonata?

P.S. After push I realized there are mobile glitches in some menus. Check out the Women's menu for a well-formatted version.

**Comment by ZanyHunter** [comment]
On second thought, maybe auto-sizing menus wouldn't be that good. Menus get harder to use. Try hovering over Huddleston Life Group then attempting to hover over a menu below. It shrinks too much. Do you have any other ideas? In the long run, it'd be nice to not have to manually override sizes for longer menu content. Maybe have them auto-size but leave a generous minimum height for at least some consistency?

**Comment by silentsonata** [comment]
Yea I see what you mean. Maybe this expanding element is not a good choice for stuff like this? I am open to rethinking what element it should be! Another place to check is the Kids Alive page. Right now it is commented out but it is a good example of too much content for this element.

**Comment by ZanyHunter** [comment]
I love the expanding look, but yeah, it gets a little busy. However, a lot of the content has large margins, could we widen the text to make it shorter, or is that something you want to avoid?

**Comment by silentsonata** [comment]
We could do that! As long as it doesn't look crowded.

**Comment by ZanyHunter** [comment]
@silentsonata, I made the social media button changes on only Doulos and Fusion, in [issue-socialMedia](https://github.com/Cornerstone-Church/CAG-MainWebsite/tree/issue-socialMedia). Do you want to continue menu development with this issue and branch? If so I won't PR, or just PR without closing this issue.

**Comment by silentsonata** [comment]
@ZanyHunter We can do menu development in another branch. That way we can close this issue without waiting for the menus to be finished.

**Comment by silentsonata** [comment]
@ZanyHunter Did we finish this? Can I close this issue?

**Comment by ZanyHunter** [comment]
@silentsonata looks like I didn't auto-close this issue from the PR a few days ago. Yep!
