### ISSUE TITLE
Ministry Section

### ISSUE THREAD

**Issue by silentsonata** [Cornerstone-Church/CAG-MainWebsite#315]
## Time to clean things up!
Now that we are at a mostly stable place with the code, it is time to start laying things out in a way that makes sense (and hopefully works better). To start this project off, we are going to work on making all ministry sections cohesive and modern. Here is our mockup based on the women's ministry page:
![WomensMinistryMochup](https://user-images.githubusercontent.com/42839957/79459395-343c3c80-7fc1-11ea-942f-b38643cf3ecb.jpg)

**Goals:**
* Create the page in elements that can be used site wide
* Modular and mobile friendly elements

The elements will be located in `/styles/elements.css`. The names of the two elements that are being created are `flat-banner` for the banner and `flat-tile` for the box element.

Two elements will be created. One element for the banner section similar to the image above, and the second would be the boxes under the banner that would link to classes or other pages.

**Comment by silentsonata** [comment]
@ZanyHunter Yo nice job with this!! Question though....When the width of the screen is at 1204px or greater the right column of elements becomes smaller in width than the other ones? But besides that excellent translation from the concept!

**Comment by ZanyHunter** [comment]
@silentsonata Thanks! Yeah, I think it has something to do with the grid being set to auto column width at that point to prevent it from rearranging again. I'll look into it!

**Comment by ZanyHunter** [comment]
Fixed!

**Comment by silentsonata** [comment]
Awesome! @ZanyHunter I have been applying the flat theme to all the other pages. When done with that I will merge it with master.

**Comment by silentsonata** [comment]
Alright so everything is done except the Living Free page. The content they have does not work with the new flat-tile because of how dense their details are. So I might just leave that the old design for now until we figure out something else.
