### ISSUE TITLE
Seeing cached site instead of live site

### ISSUE THREAD

**Issue by silentsonata** [Cornerstone-Church/CAG-MainWebsite#32]
When browsing the website, somethings are not loaded right because the user is holding on to a cached version of the site.

**Comment by silentsonata** [comment]
Im thinking we are just going to have to implement version checking for each source. For example if I were to update a slide on the banner (events page):
`<img src="/ref/IMAGE.jpg**?version=273**">`

We would probably have to implement this on all CSS links and also every time we change something we have to update the version number. Thoughts?

**Comment by silentsonata** [comment]
So I added ?version=NUMBER to all pages that had the style.css and interactive_style.js. Also for any image or src to media needs to have a version number for the cache to be cleared for that element.

**Comment by ZanyHunter** [comment]
Wow, I was just about to respond! Is this version number manually updated every time the media needs changing?

**Comment by silentsonata** [comment]
@ZanyHunter Yea....it's the only way I found testing that chrome will load the new media. Chrome will hang on to the media untill it sees that the source has changed. Another way is to rename the file and map to that file again.

**Comment by ZanyHunter** [comment]
@silentsonata Gotcha. Do you need testing done on any other browsers/OSes?

**Comment by silentsonata** [comment]
@ZanyHunter sure! I've done chrome, safari, and Firefox on macOS

**Comment by ZanyHunter** [comment]
@silentsonata Ok, great. I'll test with a few other combos and let you know.

**Comment by silentsonata** [comment]
@ZanyHunter Awesome!

**Comment by silentsonata** [comment]
This no longer appears to be an issue now that we have version control in order. I am going to close this issue.
