### ISSUE TITLE
Migrate to Next.js

### ISSUE THREAD

**Issue by jwr12135** [Cornerstone-Church/CAG-MainWebsite#438]
I suggest that we migrate this website to [next.js](https://nextjs.org), a modern server-side rendering [react](https://reactjs.org) framework. If approved, I can implement this myself.

Several reasons to use [next.js](https://nextjs.org):

- Interacting with React Virtual DOM increases performance by ensuring the UI updates quickly and efficiently
- Server-side rendering means better SEO (Search engine optimization) and better user experience for those who have disabled Javascript (currently, both the navigation header and the footer are not being rendered with javascript disabled)
- [Reusable components](https://reactjs.org/docs/components-and-props.html) let you split the UI into independent, reusable pieces and think about each piece in isolation
- React comes with [state and lifecycle](https://reactjs.org/docs/state-and-lifecycle.html) management built-in
- CSS support
- [JSX](https://reactjs.org/docs/introducing-jsx.html) is a syntax extension to JavaScript, which allows you to manipulate dom elements in an HTML like manner
- Automatic code-splitting and bundling significantly reduces production size
- Load different pages without reloading the whole website

What are your thoughts on this?

**Comment by silentsonata** [comment]
Thanks for the suggestion! Let me do some research into this and see if this is a direction we would want to go. If we do decide that it would be incredible if you could implement it!

**Comment by jwr12135** [comment]
I have started working on a new version of the cag website in case we do decide to use [next.js](https://nextjs.org). The repo is at [jwr12135/cag-nextjs](https://github.com/jwr12135/cag-nextjs). A demo is hosted on [vercel](https://vercel.com) at [cag-nextjs.vercel.app](https://cag-nextjs.vercel.app). Currently, the home page is the only working page.

**Comment by jwr12135** [comment]
I have added more information to [jwr12135/cag-nextjs](https://github.com/jwr12135/cag-nextjs)'s README.md file to help you understand the projects structure a little better.

**Comment by jwr12135** [comment]
Closing this since the website is being redone anyway.
