### ISSUE TITLE
COVID Guidelines out of date

### ISSUE THREAD

**Issue by ZanyHunter** [Cornerstone-Church/CAG-MainWebsite#482]
Cornerstone Bowie's attendance policies are now out of date. The branch issue-updateGuidelines has a starting point for updates reflected in the email sent out earlier today. I will not submit a PR in case @silentsonata wants to make more changes.

**Comment by silentsonata** [comment]
Thanks for this @ZanyHunter! Yeah if anyone sees anything that is not up to date go ahead and updated in that branch. Ill merge it with master either Monday or Tuesday.
