### ISSUE TITLE
Mobile café menu won't show info.

### ISSUE THREAD

**Issue by jwr12135** [Cornerstone-Church/CAG-MainWebsite#65]
Mobile café menu on [cag.org](http://cag.org/ministries/cafe) will not show the meal menus info when you tap on it.

**Comment by silentsonata** [comment]
@jwr12135 Thanks! I'm thinking it's a cache issue. If anyone finds something feel free to comment here!

**Comment by silentsonata** [comment]
Has anyone experienced any issues with this? @jwr12135

**Comment by silentsonata** [comment]
Alright have not heard anything on this issue in a while so I am going to close it as fixed.
